  notify:
    image: bobmorane/teslamate_notify:latest
    restart: always
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - CAR_ID=1
      - NTFY_TOPIC=votre_topic
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=teslamate
      - DB_USER=teslamate
      - DB_PASSWORD=password
    depends_on:
      - mosquitto
